env {
  job.name = "minio-jdbc"
  job.mode = "BATCH"
  parallelism = 1
}

source {
  S3File {
    plugin_output = "user_info_source"
    bucket = "s3a://vsp"
    path = "/user_roles.json"
    fs.s3a.endpoint= "http://192.168.11.120:9100"
    fs.s3a.aws.credentials.provider = "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
    access_key = "rccfs0pHG7wcpXbcyL9M"
    secret_key = "3UKHGXhH9Gd8EnF97HXIyhq91Cx6P2MhRgfYE04W"
    file_format_type = "json"
    skip_header_row_number = 1
    schema {
      columns = [
        { name = "userId", type = "int" }
        { name = "username", type = "string" }
        { name = "nickname", type = "string" }
        { name = "email", type = "string" }
        { name = "roleId", type = "string" }
        { name = "roleCode", type = "string" }
        { name = "roleName", type = "string" }
      ]
    }
    json_field {
          userId = "$.userId"
          username = "$.username"
          nickname = "$.nickname"
          email = "$.email"
          roleId = "$.roles[*].roleId"
          roleCode = "$.roles[*].roleCode"
          roleName = "$.roles[*].roleName"
    }
  }
}

transform {
}

sink {
  console {}
}