env {
  job.name = "paimon-jdbc-catalog"
  parallelism = 1
  job.mode = "BATCH"
}

source {
  FakeSource {
    plugin_output = "fake"
    parallelism = 1
    schema = {
      fields {
        pk_id = "bigint"
        name = "string"
        score = "int"
      }
      primaryKey {
        name = "pk_id"
        columnNames = [pk_id]
      }
    }
    rows = [
      { kind = INSERT, fields = [1, "A", 100] }
      { kind = INSERT, fields = [2, "B", 100] }
      { kind = INSERT, fields = [3, "C", 100] }
    ]
  }
}

transform {
}

sink {
  Paimon {
    plugin_input = "fake"
    catalog_name = "seatunnel_test"
    catalog_type = "jdbc"
    catalog_uri = "jdbc:mysql://192.168.11.111:3306/paimon_db"
    jdbc.user = "root"
    jdbc.password = "123456"
    warehouse = "s3a://vsp/warehouse"
    database = "ds_001"
    table = "st_test_jdbc1"
    schema_save_mode = "CREATE_SCHEMA_WHEN_NOT_EXIST"
    data_save_mode = "APPEND_DATA"
    paimon.table.primary-keys = "pk_id"
    paimon.table.write-props = {
      "bucket" = "4",
      "changelog-producer" = "input"
      "table-read.sequence-number.enabled" = "true"
    }
    paimon.hadoop.conf = {
      fs.s3a.access-key="rccfs0pHG7wcpXbcyL9M"
      fs.s3a.secret-key="3UKHGXhH9Gd8EnF97HXIyhq91Cx6P2MhRgfYE04W"
      fs.s3a.endpoint="http://192.168.11.120:9100"
      fs.s3a.path.style.access="true"
      fs.s3a.aws.credentials.provider="org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
    }
  }
}
