env {
  job.name = "mysql-paimon"
  parallelism = 1
  job.mode = "BATCH"
}

source {
  Jdbc {
    plugin_output = "mysql_source"
    driver = "com.mysql.cj.jdbc.Driver"
    url = "jdbc:mysql://192.168.11.111:3306/vsp_mock"
    user = "root"
    password = "123456"
    query = "select * from battlefield_intelligence"
  }
}

transform {
}

sink {
  Paimon {
    plugin_input = "mysql_source"
    catalog_name = "seatunnel_test"
    catalog_type = "jdbc"
    catalog_uri = "jdbc:mysql://192.168.11.111:3306/paimon_db"
    jdbc.user = "root"
    jdbc.password = "123456"
    warehouse = "s3a://vsp/warehouse"
    database = "ds_001"
    table = "ods_${table_name}"
    schema_save_mode = "CREATE_SCHEMA_WHEN_NOT_EXIST"
    data_save_mode = "DROP_DATA"
    paimon.table.write-props = {
      "bucket" = "4",
      "changelog-producer" = "input"
      "table-read.sequence-number.enabled" = "true"
      "snapshot.time-retained" = "1d"
    }
    paimon.hadoop.conf = {
      fs.s3a.access-key="rccfs0pHG7wcpXbcyL9M"
      fs.s3a.secret-key="3UKHGXhH9Gd8EnF97HXIyhq91Cx6P2MhRgfYE04W"
      fs.s3a.endpoint="http://192.168.11.120:9100"
      fs.s3a.path.style.access="true"
      fs.s3a.aws.credentials.provider="org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
    }
  }
}
